## 1. Generate Dataset variations

In [3]:
ROOT_PATH=%cd ..
ROOT_PATH='/home/vanessa/PycharmProjects/osh40'

/home/vanessa/PycharmProjects/osh40


In [4]:
import pandas as pd
import numpy as np
from utils.preprocess_data import PreprocessData

### 1.0 Create datasets

In [4]:
pd_data = PreprocessData()
SUBSET_TYPES = ['train', 'valid', 'test']
SENSOR_VALUES = [
    {'dataset_dst': 'uv_sensor/uv_only_value_{}', 'sensor': 'ultraviolet', 'path_test': '/home/vanessa/PycharmProjects/osh40/ia_model/datasets/uv_sensor/uv_only_value_{}.{}'},
    {'dataset_dst': 'dust_sensor/dust_only_value_{}', 'sensor': 'dust', 'path_test': '/home/vanessa/PycharmProjects/osh40/ia_model/datasets/dust_sensor/dust_only_value_{}.{}'},
    {'dataset_dst': 'light_sensor/light_only_value_{}', 'sensor': 'luminosity', 'path_test': '/home/vanessa/PycharmProjects/osh40/ia_model/datasets/light_sensor/light_only_value_{}.{}'},
    {'dataset_dst': 'noise_sensor/noise_only_value_{}', 'sensor': 'noise', 'path_test': '/home/vanessa/PycharmProjects/osh40/ia_model/datasets/noise_sensor/noise_only_value_{}.{}'},
    {'dataset_dst': 'hum_tmp_sensor/hum_tmp_only_value_{}', 'sensor': 'humidity,temperature', 'path_test': '/home/vanessa/PycharmProjects/osh40/ia_model/datasets/hum_tmp_sensor/hum_tmp_only_value_{}.{}'},
    {'dataset_dst': 'hum_tmp_sensor/hum_tmp_not_only_value_{}', 'sensor': 'humidity,temperature', 'path_test': '/home/vanessa/PycharmProjects/osh40/ia_model/datasets/hum_tmp_sensor/hum_tmp_not_only_value_{}.{}'}
]
    

In [5]:
# Genereate variation only_value
for subset_type in SUBSET_TYPES:
    for idx, sensor in enumerate(SENSOR_VALUES):
        if idx == 4:
            pd_data.generate_hum_tmp_dataset(dataset_src='data_sensors',
                                             dataset_dst=sensor.get('dataset_dst').format(subset_type), 
                                             schemas=sensor.get('sensor').split(','), subset_type=subset_type,
                                             only_array=True)
        elif idx == 5:
            pd_data.generate_hum_tmp_dataset(dataset_src='data_sensors',
                                             dataset_dst=sensor.get('dataset_dst').format(subset_type), 
                                             schemas=sensor.get('sensor').split(','), subset_type=subset_type,
                                             only_array=False)
        else:
            pd_data.generate_dataset(dataset_src='data_sensors',
                                     dataset_dst=sensor.get('dataset_dst').format(subset_type),
                                     sensor=sensor.get('sensor'), subset_type=subset_type, ds_format='only_values')
        
        train_df = pd.read_pickle(sensor.get('path_test').format(subset_type,'pkl'))
        print('Pandas dataset %s: \n%s' % (str(sensor.get('dataset_dst').format(subset_type)),
                                           str(train_df.head(6))))

        train_np = np.load(sensor.get('path_test').format(subset_type,'npy'), allow_pickle=True)
        print('Numpy dataset %s: \n%s' % (str(sensor.get('dataset_dst').format(subset_type)), 
                                          str(train_np[0])))
        

/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)


Pandas dataset uv_sensor/uv_only_value_train: 
   id subset_type  value  data_class
0   1       train    1.5           1
1   1       train    1.5           1
2   1       train    1.4           1
3   1       train    1.6           1
4   1       train    1.4           1
5   1       train    1.6           1
Numpy dataset uv_sensor/uv_only_value_train: 
[1.5 1.5 1.4 1.6 1.4 1.6 1. ]


/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)


Pandas dataset dust_sensor/dust_only_value_train: 
   id subset_type       value  data_class
0   1       train   7242772.0           1
1   1       train  11525648.0           1
2   1       train   8950155.0           1
3   1       train  12096088.0           1
4   1       train  23449298.0           1
5   1       train   9938180.0           1
Numpy dataset dust_sensor/dust_only_value_train: 
[7.2427720e+06 1.1525648e+07 8.9501550e+06 1.2096088e+07 2.3449298e+07
 9.9381800e+06 1.0000000e+00]


/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)


Pandas dataset light_sensor/light_only_value_train: 
   id subset_type  value  data_class
0   1       train    5.0           1
1   1       train    1.0           1
2   1       train    4.0           1
3   1       train    3.0           1
4   1       train    2.0           1
5   1       train    2.0           1
Numpy dataset light_sensor/light_only_value_train: 
[5. 1. 4. 3. 2. 2. 1.]


/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)


Pandas dataset noise_sensor/noise_only_value_train: 
   id subset_type  value  data_class
0   1       train   89.0           1
1   1       train   85.0           1
2   1       train   87.0           1
3   1       train   85.0           1
4   1       train   90.0           1
5   1       train   85.0           1
Numpy dataset noise_sensor/noise_only_value_train: 
[89. 85. 87. 85. 90. 85.  1.]


/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)
/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)


Pandas dataset hum_tmp_sensor/hum_tmp_only_value_train: 
   id humidity_subset_type  humidity_value  humidity_class  temperature_value
0   1                train            68.0               1               21.3
1   1                train            70.0               1               20.7
2   1                train            68.0               1               21.7
3   1                train            69.0               1               19.0
4   1                train            71.0               1               19.3
5   1                train            68.0               1               20.2
Numpy dataset hum_tmp_sensor/hum_tmp_only_value_train: 
[68.  21.3 70.  20.7 68.  21.7 69.  19.  71.  19.3 68.  20.2  1. ]


/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)
/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)


Pandas dataset hum_tmp_sensor/hum_tmp_not_only_value_train: 
   id humidity_subset_type  humidity_value  humidity_class  temperature_value
0   1                train            68.0               1               21.3
1   1                train            70.0               1               20.7
2   1                train            68.0               1               21.7
3   1                train            69.0               1               19.0
4   1                train            71.0               1               19.3
5   1                train            68.0               1               20.2
Numpy dataset hum_tmp_sensor/hum_tmp_not_only_value_train: 
[68.  70.  68.  69.  71.  68.  21.3 20.7 21.7 19.  19.3 20.2  1. ]


/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)


Pandas dataset uv_sensor/uv_only_value_valid: 
     id subset_type  value  data_class
0  2161       valid    1.5           1
1  2161       valid    1.4           1
2  2161       valid    1.5           1
3  2161       valid    1.4           1
4  2161       valid    1.6           1
5  2161       valid    1.4           1
Numpy dataset uv_sensor/uv_only_value_valid: 
[1.5 1.4 1.5 1.4 1.6 1.4 1. ]


/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)


Pandas dataset dust_sensor/dust_only_value_valid: 
     id subset_type       value  data_class
0  2161       valid   2614217.0           1
1  2161       valid  17847121.0           1
2  2161       valid  18105098.0           1
3  2161       valid  27882024.0           1
4  2161       valid  24957103.0           1
5  2161       valid  23118705.0           1
Numpy dataset dust_sensor/dust_only_value_valid: 
[2.6142170e+06 1.7847121e+07 1.8105098e+07 2.7882024e+07 2.4957103e+07
 2.3118705e+07 1.0000000e+00]


/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)


Pandas dataset light_sensor/light_only_value_valid: 
     id subset_type  value  data_class
0  2161       valid    4.0           1
1  2161       valid    1.0           1
2  2161       valid    2.0           1
3  2161       valid    3.0           1
4  2161       valid    5.0           1
5  2161       valid    5.0           1
Numpy dataset light_sensor/light_only_value_valid: 
[4. 1. 2. 3. 5. 5. 1.]


/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)


Pandas dataset noise_sensor/noise_only_value_valid: 
     id subset_type  value  data_class
0  2161       valid   88.0           1
1  2161       valid   86.0           1
2  2161       valid   90.0           1
3  2161       valid   87.0           1
4  2161       valid   89.0           1
5  2161       valid   89.0           1
Numpy dataset noise_sensor/noise_only_value_valid: 
[88. 86. 90. 87. 89. 89.  1.]


/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)
/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)


Pandas dataset hum_tmp_sensor/hum_tmp_only_value_valid: 
     id humidity_subset_type  humidity_value  humidity_class  \
0  2161                valid            69.0               1   
1  2161                valid            71.0               1   
2  2161                valid            71.0               1   
3  2161                valid            68.0               1   
4  2161                valid            68.0               1   
5  2161                valid            71.0               1   

   temperature_value  
0               20.6  
1               19.6  
2               19.8  
3               19.9  
4               19.7  
5               21.1  
Numpy dataset hum_tmp_sensor/hum_tmp_only_value_valid: 
[69.  20.6 71.  19.6 71.  19.8 68.  19.9 68.  19.7 71.  21.1  1. ]


/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)
/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)


Pandas dataset hum_tmp_sensor/hum_tmp_not_only_value_valid: 
     id humidity_subset_type  humidity_value  humidity_class  \
0  2161                valid            69.0               1   
1  2161                valid            71.0               1   
2  2161                valid            71.0               1   
3  2161                valid            68.0               1   
4  2161                valid            68.0               1   
5  2161                valid            71.0               1   

   temperature_value  
0               20.6  
1               19.6  
2               19.8  
3               19.9  
4               19.7  
5               21.1  
Numpy dataset hum_tmp_sensor/hum_tmp_not_only_value_valid: 
[69.  71.  71.  68.  68.  71.  20.6 19.6 19.8 19.9 19.7 21.1  1. ]


/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)


Pandas dataset uv_sensor/uv_only_value_test: 
     id subset_type  value  data_class
0  1081        test    1.4           1
1  1081        test    1.3           1
2  1081        test    1.5           1
3  1081        test    1.4           1
4  1081        test    1.5           1
5  1081        test    1.6           1
Numpy dataset uv_sensor/uv_only_value_test: 
[1.4 1.3 1.5 1.4 1.5 1.6 1. ]


/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)


Pandas dataset dust_sensor/dust_only_value_test: 
     id subset_type       value  data_class
0  1081        test  17591136.0           1
1  1081        test  19987795.0           1
2  1081        test  27877454.0           1
3  1081        test   1182970.0           1
4  1081        test   6364529.0           1
5  1081        test  13236230.0           1
Numpy dataset dust_sensor/dust_only_value_test: 
[1.7591136e+07 1.9987795e+07 2.7877454e+07 1.1829700e+06 6.3645290e+06
 1.3236230e+07 1.0000000e+00]


/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)


Pandas dataset light_sensor/light_only_value_test: 
     id subset_type  value  data_class
0  1081        test    4.0           1
1  1081        test    1.0           1
2  1081        test    3.0           1
3  1081        test    2.0           1
4  1081        test    5.0           1
5  1081        test    5.0           1
Numpy dataset light_sensor/light_only_value_test: 
[4. 1. 3. 2. 5. 5. 1.]


/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)


Pandas dataset noise_sensor/noise_only_value_test: 
     id subset_type  value  data_class
0  1081        test   87.0           1
1  1081        test   85.0           1
2  1081        test   88.0           1
3  1081        test   87.0           1
4  1081        test   86.0           1
5  1081        test   89.0           1
Numpy dataset noise_sensor/noise_only_value_test: 
[87. 85. 88. 87. 86. 89.  1.]


/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)
/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)


Pandas dataset hum_tmp_sensor/hum_tmp_only_value_test: 
     id humidity_subset_type  humidity_value  humidity_class  \
0  1081                 test            68.0               1   
1  1081                 test            71.0               1   
2  1081                 test            70.0               1   
3  1081                 test            69.0               1   
4  1081                 test            71.0               1   
5  1081                 test            70.0               1   

   temperature_value  
0               21.1  
1               20.3  
2               19.6  
3               21.7  
4               21.5  
5               21.0  
Numpy dataset hum_tmp_sensor/hum_tmp_only_value_test: 
[68.  21.1 71.  20.3 70.  19.6 69.  21.7 71.  21.5 70.  21.   1. ]


/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)
/home/vanessa/PycharmProjects/osh40/ia_model/connectors/postgres.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_df = pd.read_sql_query(sql_command, conn)


Pandas dataset hum_tmp_sensor/hum_tmp_not_only_value_test: 
     id humidity_subset_type  humidity_value  humidity_class  \
0  1081                 test            68.0               1   
1  1081                 test            71.0               1   
2  1081                 test            70.0               1   
3  1081                 test            69.0               1   
4  1081                 test            71.0               1   
5  1081                 test            70.0               1   

   temperature_value  
0               21.1  
1               20.3  
2               19.6  
3               21.7  
4               21.5  
5               21.0  
Numpy dataset hum_tmp_sensor/hum_tmp_not_only_value_test: 
[68.  71.  70.  69.  71.  70.  21.1 20.3 19.6 21.7 21.5 21.   1. ]
